server:
  port: 9001


eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001:7001/eureka/,http://eureka-7002:7002/eureka/,http://eureka-7003:7003/eureka/
  instance:
    instance-id: cloud-zuul-9001